#!/bin/bash

if [ "$1" = "" ]; then
	echo "error: need mc-number"
	exit 1
fi

echo "docker-compose -f compose-mc$1.yml up -d && docker logs -f mc$1"
docker-compose -p mc$1 -f compose-mc$1.yml up -d && docker logs -f mc$1
