#!/bin/bash

cwd=$(dirname $(readlink -f $0))

function header {
    cat $cwd/header.html
}

function h1 {
    echo "<h1>$1</h1>"
}

function h2 {
    echo "<h2>$1</h2>"
}

function tablestart {
    echo "<table>"
}

function tableend {
    echo "</table>"
}

function whitelist {
	docker exec -i mc$1 rcon-cli whitelist list | sort | sed -e 's/^.*: //' -e 's/, /\n/g'
}

function users {
	docker exec -i mc$1 rcon-cli list | sort | sed -e 's/^.*: //' -e 's/, /\n/g'
}

function lastlog {
	docker logs -t mc$1 | grep -v RCON | tail -n 20
}

function formatps {
    sed -e 's/^.* itz/<tr><td>itz/' \
        -e 's/  .*ago[ ]*/<\/td><td>/' \
        -e 's/ [0-9][0-9]*.tcp.*->/ /' \
        -e 's/\/tcp//' \
        -e 's/) */)<\/td><td>/' \
        -e 's/ *mc/<\/td><td>mc/' \
        -e 's/$/<\/td><\/tr>/'
}


function check {
	echo "================================================"
	echo "| Inspect MC$1 |"
	echo "==============="
	echo ""
	echo "WHITELIST:"
	echo "----------"
	whitelist $1
	echo ""
	echo "ACTIVE-USERS:"
	echo "-------------"
	users $1
	echo ""
	echo "LAST-LOG:"
	echo "----------"
	lastlog $1
	echo ""
}

header
h1 "Minecraft Server Information"
h2 "Server Status"
tablestart
docker ps | formatps
tableend

#check 1
#check 2
#check 3
